// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvyvkyspbqcqcsgdvzjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2eXZreXNwYnFjcWNzZ2R2empwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjUzNTEsImV4cCI6MjA2NjA0MTM1MX0.INWnez88XgQs4R5yo685k86_2A92auI_qgCFt3_FJIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);